/soc/oplus,monitor/track,nominal_fcc1 0x1838
/soc/oplus,monitor/track,gauge_max_dischg_curr 0x1b58
/soc/oplus,monitor/track,nominal_qmax1 0x1838
/soc/oplus,comm/oplus,reserve_chg_soc 0x00
a /soc/oplus,comm/oplus,reserve_dis_soc 0x00
/soc/oplus,monitor/oplus,chg_shutdown_max_mv 0xa8c
/soc/oplus,monitor/oplus_spec,vbat_uv_thr_mv 0xaf0
/soc/oplus,comm/oplus_spec,full-pre-ffc-mv 0x1208
/soc/oplus,comm/oplus_spec,vbat_uv_thr_mv 0xaf0
/soc/oplus,comm/oplus,chg_shutdown_max_mv 0xa8c