/soc/oplus,monitor/track,nominal_fcc1 0x1838
/soc/oplus,monitor/track,gauge_max_dischg_curr 0x1b58
/soc/oplus,monitor/track,nominal_qmax1 0x1838
/soc/oplus,comm/oplus,reserve_chg_soc 0x00
/soc/oplus,comm/oplus_spec,full-pre-ffc-mv 0x1208
/soc/oplus,comm/oplus_spec,vbat_uv_thr_mv 0xaf0
/soc/oplus,comm/oplus,chg_shutdown_max_mv 0xa8c
/soc/oplus,comm/oplus_spec,vbat_charging_uv_thr_mv 0xa8c
/soc/oplus,comm/oplus_spec,wired-ffc-fv-cutoff-mv 0x1208 0x1208 0x11e9 0x11e9 0x11c6 0x11c6 0x11c6 0x11c1 0x11ad 0x11c6 0x11bc 0x11a8 0x11c1 0x11b7 0x11a3
/soc/oplus,comm/oplus_spec,fv-mv 0x1216 0x1208 0x1208 0x1194 0x1194 0x1194 0x117b 0x1022 0x1022
/soc/oplus,comm/oplus_spec,vbatt-ov-thr-mv 0x1208
/soc/oplus,monitor/track,general_chg_break_t_thd 0x258
/soc/oplus,monitor/track,gauge_max_cell_vol 0x1208
