/soc/oplus,ufcs_charge/oplus,ufcs_strategy_batt_high_temp 0x1c7 0x1d6 0x1e0 0x1c7 0x1cc 0x1e0
/soc/oplus,ufcs_charge/oplus,ufcs_charge_strategy_temp 0x00 0x32 0x78 0xa0 0x12c 0x1cc 0x1e0
/soc/oplus,pps_charge/oplus,pps_strategy_batt_high_temp 0x1c2 0x1d6 0x1e0 0x1b8 0x1cc 0x1d6
/soc/oplus,pps_charge/oplus,pps_charge_strategy_temp 0x00 0x32 0x78 0xa0 0x15e 0x1e0 0x1e0
/soc/oplus,pps_charge/pps_charge_third_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x12c 0x1cc 0x1e0
/soc/oplus,pps_charge/pps_charge_oplus_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x12c 0x1cc 0x1e0
/soc/oplus,ufcs_charge/ufcs_charge_third_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x12c 0x1cc 0x1e0
/soc/oplus,ufcs_charge/ufcs_charge_oplus_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x12c 0x1cc 0x1e0
