d /soc/oplus,mms_gauge/deep_spec,vbat_soc
d /soc/oplus,mms_gauge/deep_spec,count_thr
d /soc/oplus,mms_gauge/deep_spec,ddrc_strategy_name
d /soc/oplus,mms_gauge/deep_spec,uv_thr
d /soc/oplus,mms_gauge/deep_spec,term_coeff
d /soc/oplus,mms_gauge/deep_spec,count_step
d /soc/oplus,mms_gauge/deep_spec,volt_step
/soc/oplus,wired/oplus_spec,non-standard-ibatmax-ma 0x384
