c /soc/author
a /soc/author/name author
a /soc/author/author CoolAPK@BrokeStar
a /soc/author/homo [11 45 14 19 19 81 00]
a /soc/author/special_thanks 所有充电相关补丁来源:CoolAPK@bybycode\n一加13t解容补丁来源:CoolAPK@鲸鱼不游
