r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA569_P_3_A0019_dsc_cmd/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_90
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA569_P_3_A0019_dsc_cmd_evt/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_90
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA569_P_3_A0019_dsc_cmd_evb/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_90
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_BF262_P_3_A0021_dsc_cmd/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_90
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA545_P_3_A0005_dsc_cmd/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_90
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA569_P_3_A0019_dsc_cmd/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_60
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA569_P_3_A0019_dsc_cmd_evt/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_60
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA569_P_3_A0019_dsc_cmd_evb/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_60
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_BF262_P_3_A0021_dsc_cmd/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_60
r /soc/qcom,mdss_mdp@ae00000/qcom,mdss_dsi_panel_AA545_P_3_A0005_dsc_cmd/qcom,mdss-dsi-display-timings/timing@wqhd_sdc_60
