r /soc/oplus,mms_gauge/silicon_p_770
r /soc/oplus,mms_gauge/ddrc_strategy
r /soc/oplus,mms_gauge/deep_spec,ddbc_curve
d /soc/oplus,mms_gauge/deep_spec,support
d /soc/oplus,mms_gauge/deep_spec,uv_thr
d /soc/oplus,mms_gauge/deep_spec,count_thr
d /soc/oplus,mms_gauge/deep_spec,vbat_soc
d /soc/oplus,mms_gauge/deep_spec,count_step
d /soc/oplus,mms_gauge/deep_spec,term_coeff
d /soc/oplus,mms_gauge/deep_spec,ddrc_strategy_name
d /soc/oplus,mms_gauge/deep_spec,volt_step
