/soc/oplus,ufcs_charge/silicon_p_770/oplus,ufcs_strategy_batt_high_temp 0x1c2 0x1d6 0x1e0 0x1b8 0x1cc 0x1d6
/soc/oplus,ufcs_charge/silicon_p_770/oplus,ufcs_strategy_high_current 0x238c 0x238c 0x1964 0x238c 0x238c 0x238c
/soc/oplus,ufcs_charge/silicon_p_770/oplus,ufcs_charge_strategy_temp 0x00 0x32 0x78 0xa0 0x15e 0x1e0 0x1fe
/soc/oplus,pps_charge/silicon_p_770/oplus,pps_strategy_batt_high_temp 0x1c2 0x1d6 0x1e0 0x1b8 0x1cc 0x1d6
/soc/oplus,pps_charge/silicon_p_770/oplus,pps_charge_strategy_temp 0x00 0x32 0x78 0xa0 0x15e 0x1e0 0x1fe
/soc/oplus,pps_charge/silicon_p_770/pps_charge_third_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x15e 0x1e0 0x1fe
/soc/oplus,pps_charge/silicon_p_770/pps_charge_oplus_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x15e 0x1e0 0x1fe
/soc/oplus,ufcs_charge/silicon_p_770/ufcs_charge_third_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x15e 0x1e0 0x1fe
/soc/oplus,ufcs_charge/silicon_p_770/ufcs_charge_oplus_strategy/oplus,temp_range 0x00 0x32 0x78 0xa0 0xd2 0x15e 0x1e0 0x1fe
