# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_AUTHORITY_CTRL)		+= auth_qos_ctrl.o
auth_qos_ctrl-$(CONFIG_AUTHORITY_CTRL)	+= auth_ctrl.o
auth_qos_ctrl-$(CONFIG_QOS_CTRL)	+= qos_ctrl.o
auth_qos_ctrl-$(CONFIG_AUTH_QOS_DEBUG)	+= auth_qos_debug.o
